import type { DocumentTemplateData } from "./document-types";

export const documentTemplates: DocumentTemplateData[] = [
  // ============================================================
  // LEGAL TEMPLATES
  // ============================================================

  // 1. NDA
  {
    name: "NDA",
    slug: "nda",
    category: "LEGAL",
    description:
      "Non-disclosure agreement to protect confidential project information shared with contractors, clients, or partners.",
    requiresSignature: true,
    isExternal: true,
    fieldSchema: {
      sections: [
        {
          title: "Agreement Details",
          description: undefined,
          fields: [
            {
              name: "effectiveDate",
              type: "date",
              label: "Effective Date",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "disclosingParty",
              type: "text",
              label: "Disclosing Party",
              required: true,
              prefilledByAdmin: true,
              defaultValue: "Geared Like A Machine LLC",
            },
            {
              name: "scope",
              type: "textarea",
              label: "Scope of Confidential Information",
              required: true,
              prefilledByAdmin: true,
              placeholder:
                "Describe the type of confidential information being shared",
            },
            {
              name: "duration",
              type: "select",
              label: "Duration",
              required: true,
              prefilledByAdmin: true,
              options: [
                { label: "1 Year", value: "1yr" },
                { label: "2 Years", value: "2yr" },
                { label: "3 Years", value: "3yr" },
                { label: "5 Years", value: "5yr" },
                { label: "Perpetual", value: "perpetual" },
              ],
            },
          ],
        },
        {
          title: "Receiving Party Information",
          description: undefined,
          fields: [
            {
              name: "receivingPartyName",
              type: "text",
              label: "Full Name",
              required: true,
              prefilledByAdmin: false,
              placeholder: "Legal name of the receiving party",
            },
            {
              name: "receivingPartyTitle",
              type: "text",
              label: "Title",
              required: false,
              prefilledByAdmin: false,
            },
            {
              name: "receivingPartyCompany",
              type: "text",
              label: "Company",
              required: false,
              prefilledByAdmin: false,
            },
            {
              name: "receivingPartyEmail",
              type: "email",
              label: "Email Address",
              required: true,
              prefilledByAdmin: false,
            },
            {
              name: "receivingPartyAddress",
              type: "address",
              label: "Address",
              required: true,
              prefilledByAdmin: false,
            },
          ],
        },
      ],
    },
  },

  // 2. Independent Contractor Agreement
  {
    name: "Independent Contractor Agreement",
    slug: "independent-contractor-agreement",
    category: "LEGAL",
    description:
      "Agreement establishing the terms and scope of work for independent contractors hired on a project basis.",
    requiresSignature: true,
    isExternal: true,
    fieldSchema: {
      sections: [
        {
          title: "Engagement Details",
          description: undefined,
          fields: [
            {
              name: "projectName",
              type: "text",
              label: "Project Name",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "scopeOfWork",
              type: "textarea",
              label: "Scope of Work",
              required: true,
              prefilledByAdmin: true,
              placeholder: "Detailed description of services to be performed",
            },
            {
              name: "startDate",
              type: "date",
              label: "Start Date",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "endDate",
              type: "date",
              label: "End Date",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "compensation",
              type: "currency",
              label: "Compensation",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "paymentTerms",
              type: "select",
              label: "Payment Terms",
              required: true,
              prefilledByAdmin: true,
              options: [
                { label: "Net 15", value: "net_15" },
                { label: "Net 30", value: "net_30" },
                { label: "Upon Completion", value: "upon_completion" },
                { label: "50/50", value: "50_50" },
              ],
            },
            {
              name: "additionalTerms",
              type: "textarea",
              label: "Additional Terms",
              required: false,
              prefilledByAdmin: true,
              placeholder: "Any additional terms or conditions",
            },
          ],
        },
        {
          title: "Contractor Information",
          description: undefined,
          fields: [
            {
              name: "contractorName",
              type: "text",
              label: "Full Legal Name",
              required: true,
              prefilledByAdmin: false,
            },
            {
              name: "contractorAddress",
              type: "address",
              label: "Address",
              required: true,
              prefilledByAdmin: false,
            },
            {
              name: "contractorEmail",
              type: "email",
              label: "Email Address",
              required: true,
              prefilledByAdmin: false,
            },
            {
              name: "contractorPhone",
              type: "phone",
              label: "Phone Number",
              required: true,
              prefilledByAdmin: false,
            },
            {
              name: "taxId",
              type: "text",
              label: "Tax ID / EIN",
              required: true,
              prefilledByAdmin: false,
              helpText: "Used for 1099 reporting",
            },
            {
              name: "w9Acknowledgment",
              type: "checkbox",
              label: "I will provide a completed W-9 form",
              required: true,
              prefilledByAdmin: false,
            },
          ],
        },
      ],
    },
  },

  // 3. Talent Release
  {
    name: "Talent Release",
    slug: "talent-release",
    category: "LEGAL",
    description:
      "Release form granting permission to use a talent's likeness, voice, or performance in production materials.",
    requiresSignature: true,
    isExternal: true,
    fieldSchema: {
      sections: [
        {
          title: "Production Details",
          description: undefined,
          fields: [
            {
              name: "productionName",
              type: "text",
              label: "Production Name",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "shootDate",
              type: "date",
              label: "Shoot Date",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "shootLocation",
              type: "text",
              label: "Shoot Location",
              required: false,
              prefilledByAdmin: true,
            },
            {
              name: "usageRights",
              type: "checkboxGroup",
              label: "Usage Rights",
              required: true,
              prefilledByAdmin: true,
              options: [
                { label: "Broadcast", value: "broadcast" },
                { label: "Digital", value: "digital" },
                { label: "Print", value: "print" },
                { label: "Internal", value: "internal" },
                { label: "All Media", value: "all_media" },
              ],
            },
            {
              name: "compensation",
              type: "select",
              label: "Compensation Type",
              required: true,
              prefilledByAdmin: true,
              options: [
                { label: "None", value: "none" },
                { label: "Flat Fee", value: "flat_fee" },
                { label: "Day Rate", value: "day_rate" },
              ],
            },
            {
              name: "compensationAmount",
              type: "currency",
              label: "Compensation Amount",
              required: false,
              prefilledByAdmin: true,
            },
          ],
        },
        {
          title: "Talent Information",
          description: undefined,
          fields: [
            {
              name: "talentName",
              type: "text",
              label: "Full Name",
              required: true,
              prefilledByAdmin: false,
            },
            {
              name: "talentAddress",
              type: "address",
              label: "Address",
              required: true,
              prefilledByAdmin: false,
            },
            {
              name: "talentPhone",
              type: "phone",
              label: "Phone Number",
              required: false,
              prefilledByAdmin: false,
            },
            {
              name: "talentEmail",
              type: "email",
              label: "Email Address",
              required: false,
              prefilledByAdmin: false,
            },
            {
              name: "isMinor",
              type: "checkbox",
              label: "Talent is a minor (under 18)",
              required: false,
              prefilledByAdmin: false,
            },
            {
              name: "guardianName",
              type: "text",
              label: "Parent/Guardian Name",
              required: false,
              prefilledByAdmin: false,
              helpText: "Required if talent is a minor",
            },
          ],
        },
      ],
    },
  },

  // 4. Location Release
  {
    name: "Location Release",
    slug: "location-release",
    category: "LEGAL",
    description:
      "Agreement granting permission to film at a specific location, including terms of access and any location fees.",
    requiresSignature: true,
    isExternal: true,
    fieldSchema: {
      sections: [
        {
          title: "Production Details",
          description: undefined,
          fields: [
            {
              name: "productionName",
              type: "text",
              label: "Production Name",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "productionCompany",
              type: "text",
              label: "Production Company",
              required: true,
              prefilledByAdmin: true,
              defaultValue: "Geared Like A Machine LLC",
            },
            {
              name: "shootDates",
              type: "dateRange",
              label: "Shoot Dates",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "shootTimes",
              type: "text",
              label: "Shoot Times",
              required: false,
              prefilledByAdmin: true,
              placeholder: "e.g. 6:00 AM - 8:00 PM",
            },
            {
              name: "locationDescription",
              type: "textarea",
              label: "Location Description",
              required: true,
              prefilledByAdmin: true,
              placeholder:
                "Full address and description of the areas to be used",
            },
            {
              name: "crewSize",
              type: "number",
              label: "Estimated Crew Size",
              required: false,
              prefilledByAdmin: true,
            },
            {
              name: "locationFee",
              type: "currency",
              label: "Location Fee",
              required: false,
              prefilledByAdmin: true,
            },
          ],
        },
        {
          title: "Property Owner",
          description: undefined,
          fields: [
            {
              name: "ownerName",
              type: "text",
              label: "Property Owner Name",
              required: true,
              prefilledByAdmin: false,
            },
            {
              name: "ownerTitle",
              type: "text",
              label: "Title",
              required: false,
              prefilledByAdmin: false,
            },
            {
              name: "ownerAddress",
              type: "address",
              label: "Address",
              required: true,
              prefilledByAdmin: false,
            },
            {
              name: "ownerPhone",
              type: "phone",
              label: "Phone Number",
              required: true,
              prefilledByAdmin: false,
            },
            {
              name: "ownerEmail",
              type: "email",
              label: "Email Address",
              required: false,
              prefilledByAdmin: false,
            },
            {
              name: "specialConditions",
              type: "textarea",
              label: "Special Conditions",
              required: false,
              prefilledByAdmin: false,
              placeholder:
                "Any restrictions, requirements, or special conditions for use",
            },
          ],
        },
      ],
    },
  },

  // 5. Music License Agreement
  {
    name: "Music License Agreement",
    slug: "music-license-agreement",
    category: "LEGAL",
    description:
      "License agreement for the use of music tracks in a production, specifying territory, duration, and usage rights.",
    requiresSignature: true,
    isExternal: true,
    fieldSchema: {
      sections: [
        {
          title: "Production & Track Details",
          description: undefined,
          fields: [
            {
              name: "productionName",
              type: "text",
              label: "Production Name",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "trackTitle",
              type: "text",
              label: "Track Title",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "artist",
              type: "text",
              label: "Artist / Composer",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "usageType",
              type: "checkboxGroup",
              label: "Usage Type",
              required: true,
              prefilledByAdmin: true,
              options: [
                { label: "Background", value: "background" },
                { label: "Featured", value: "featured" },
                { label: "Theme", value: "theme" },
                { label: "Promo", value: "promo" },
              ],
            },
            {
              name: "territory",
              type: "select",
              label: "Territory",
              required: true,
              prefilledByAdmin: true,
              options: [
                { label: "Worldwide", value: "worldwide" },
                { label: "United States Only", value: "us_only" },
                { label: "North America", value: "north_america" },
                { label: "Custom", value: "custom" },
              ],
            },
            {
              name: "customTerritory",
              type: "text",
              label: "Custom Territory",
              required: false,
              prefilledByAdmin: true,
              placeholder: "Specify if territory is 'Custom'",
            },
            {
              name: "licenseDuration",
              type: "text",
              label: "License Duration",
              required: true,
              prefilledByAdmin: true,
              placeholder: "e.g. In perpetuity, 1 year, 6 months",
            },
            {
              name: "licenseFee",
              type: "currency",
              label: "License Fee",
              required: true,
              prefilledByAdmin: true,
            },
          ],
        },
        {
          title: "Licensor Information",
          description: undefined,
          fields: [
            {
              name: "licensorName",
              type: "text",
              label: "Licensor Name",
              required: true,
              prefilledByAdmin: false,
            },
            {
              name: "licensorCompany",
              type: "text",
              label: "Company / Label",
              required: false,
              prefilledByAdmin: false,
            },
            {
              name: "licensorEmail",
              type: "email",
              label: "Email Address",
              required: true,
              prefilledByAdmin: false,
            },
            {
              name: "licensorAddress",
              type: "address",
              label: "Address",
              required: true,
              prefilledByAdmin: false,
            },
            {
              name: "proAffiliation",
              type: "text",
              label: "PRO Affiliation",
              required: false,
              prefilledByAdmin: false,
              helpText: "e.g. ASCAP, BMI, SESAC",
            },
          ],
        },
      ],
    },
  },

  // 6. Equipment Rental Agreement
  {
    name: "Equipment Rental Agreement",
    slug: "equipment-rental-agreement",
    category: "LEGAL",
    description:
      "Rental agreement covering terms, insurance requirements, and liability for equipment rented to clients or crew.",
    requiresSignature: true,
    isExternal: true,
    fieldSchema: {
      sections: [
        {
          title: "Rental Details",
          description: undefined,
          fields: [
            {
              name: "rentalPeriod",
              type: "dateRange",
              label: "Rental Period",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "equipmentList",
              type: "textarea",
              label: "Equipment List",
              required: true,
              prefilledByAdmin: true,
              placeholder:
                "List all equipment items with quantities and serial numbers",
            },
            {
              name: "totalRentalFee",
              type: "currency",
              label: "Total Rental Fee",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "securityDeposit",
              type: "currency",
              label: "Security Deposit",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "pickupLocation",
              type: "text",
              label: "Pickup Location",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "returnDate",
              type: "date",
              label: "Return Date",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "lateFeePerDay",
              type: "currency",
              label: "Late Fee Per Day",
              required: false,
              prefilledByAdmin: true,
            },
          ],
        },
        {
          title: "Renter Information",
          description: undefined,
          fields: [
            {
              name: "renterName",
              type: "text",
              label: "Full Name",
              required: true,
              prefilledByAdmin: false,
            },
            {
              name: "renterCompany",
              type: "text",
              label: "Company",
              required: false,
              prefilledByAdmin: false,
            },
            {
              name: "renterAddress",
              type: "address",
              label: "Address",
              required: true,
              prefilledByAdmin: false,
            },
            {
              name: "renterPhone",
              type: "phone",
              label: "Phone Number",
              required: true,
              prefilledByAdmin: false,
            },
            {
              name: "renterEmail",
              type: "email",
              label: "Email Address",
              required: true,
              prefilledByAdmin: false,
            },
            {
              name: "insuranceProvider",
              type: "text",
              label: "Insurance Provider",
              required: true,
              prefilledByAdmin: false,
              helpText:
                "Proof of insurance covering rented equipment is required",
            },
            {
              name: "insurancePolicyNumber",
              type: "text",
              label: "Insurance Policy Number",
              required: true,
              prefilledByAdmin: false,
            },
            {
              name: "insuranceExpiration",
              type: "date",
              label: "Insurance Expiration Date",
              required: true,
              prefilledByAdmin: false,
            },
            {
              name: "driversLicense",
              type: "text",
              label: "Driver's License Number",
              required: true,
              prefilledByAdmin: false,
            },
          ],
        },
      ],
    },
  },

  // 7. Master Service Agreement
  {
    name: "Master Service Agreement",
    slug: "master-service-agreement",
    category: "LEGAL",
    description:
      "Umbrella agreement establishing the general terms and conditions for an ongoing client relationship across multiple projects.",
    requiresSignature: true,
    isExternal: true,
    fieldSchema: {
      sections: [
        {
          title: "Agreement Terms",
          description: undefined,
          fields: [
            {
              name: "effectiveDate",
              type: "date",
              label: "Effective Date",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "serviceDescription",
              type: "textarea",
              label: "Description of Services",
              required: true,
              prefilledByAdmin: true,
              placeholder:
                "General description of services covered under this agreement",
            },
            {
              name: "paymentTerms",
              type: "select",
              label: "Payment Terms",
              required: true,
              prefilledByAdmin: true,
              options: [
                { label: "Net 15", value: "net_15" },
                { label: "Net 30", value: "net_30" },
                { label: "Net 45", value: "net_45" },
                { label: "Net 60", value: "net_60" },
              ],
            },
            {
              name: "lateFeePercent",
              type: "number",
              label: "Late Fee Percentage",
              required: true,
              prefilledByAdmin: true,
              defaultValue: 1.5,
              helpText: "Monthly percentage applied to overdue balances",
            },
            {
              name: "termLength",
              type: "select",
              label: "Term Length",
              required: true,
              prefilledByAdmin: true,
              options: [
                { label: "1 Year", value: "1yr" },
                { label: "2 Years", value: "2yr" },
                { label: "Project-Based", value: "project_based" },
              ],
            },
            {
              name: "additionalTerms",
              type: "textarea",
              label: "Additional Terms",
              required: false,
              prefilledByAdmin: true,
            },
          ],
        },
        {
          title: "Client Information",
          description: undefined,
          fields: [
            {
              name: "clientName",
              type: "text",
              label: "Client Name",
              required: true,
              prefilledByAdmin: false,
            },
            {
              name: "clientCompany",
              type: "text",
              label: "Company",
              required: true,
              prefilledByAdmin: false,
            },
            {
              name: "clientTitle",
              type: "text",
              label: "Title",
              required: true,
              prefilledByAdmin: false,
            },
            {
              name: "clientEmail",
              type: "email",
              label: "Email Address",
              required: true,
              prefilledByAdmin: false,
            },
            {
              name: "clientPhone",
              type: "phone",
              label: "Phone Number",
              required: false,
              prefilledByAdmin: false,
            },
            {
              name: "clientAddress",
              type: "address",
              label: "Address",
              required: true,
              prefilledByAdmin: false,
            },
          ],
        },
      ],
    },
  },

  // 8. Production Agreement
  {
    name: "Production Agreement",
    slug: "production-agreement",
    category: "LEGAL",
    description:
      "Comprehensive agreement covering the full scope of a production project, including deliverables, budget, payment schedule, and revision terms.",
    requiresSignature: true,
    isExternal: true,
    fieldSchema: {
      sections: [
        {
          title: "Project Details",
          description: undefined,
          fields: [
            {
              name: "projectName",
              type: "text",
              label: "Project Name",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "projectDescription",
              type: "textarea",
              label: "Project Description",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "deliverables",
              type: "textarea",
              label: "Deliverables",
              required: true,
              prefilledByAdmin: true,
              placeholder:
                "List all deliverables with specifications (format, length, resolution, etc.)",
            },
            {
              name: "productionDates",
              type: "dateRange",
              label: "Production Dates",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "deliveryDate",
              type: "date",
              label: "Final Delivery Date",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "totalBudget",
              type: "currency",
              label: "Total Budget",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "paymentSchedule",
              type: "select",
              label: "Payment Schedule",
              required: true,
              prefilledByAdmin: true,
              options: [
                { label: "50/50", value: "50_50" },
                { label: "50/25/25", value: "50_25_25" },
                { label: "Thirds", value: "thirds" },
                { label: "100% Upfront", value: "100_upfront" },
                { label: "Net 30", value: "net_30" },
              ],
            },
            {
              name: "revisionRounds",
              type: "number",
              label: "Included Revision Rounds",
              required: true,
              prefilledByAdmin: true,
              defaultValue: 2,
            },
            {
              name: "additionalRevisionRate",
              type: "currency",
              label: "Additional Revision Rate",
              required: true,
              prefilledByAdmin: true,
              defaultValue: 200,
              helpText: "Per-round rate for revisions beyond the included rounds",
            },
            {
              name: "additionalTerms",
              type: "textarea",
              label: "Additional Terms",
              required: false,
              prefilledByAdmin: true,
            },
          ],
        },
        {
          title: "Client Information",
          description: undefined,
          fields: [
            {
              name: "clientName",
              type: "text",
              label: "Client Name",
              required: true,
              prefilledByAdmin: false,
            },
            {
              name: "clientCompany",
              type: "text",
              label: "Company",
              required: true,
              prefilledByAdmin: false,
            },
            {
              name: "clientTitle",
              type: "text",
              label: "Title",
              required: true,
              prefilledByAdmin: false,
            },
            {
              name: "clientEmail",
              type: "email",
              label: "Email Address",
              required: true,
              prefilledByAdmin: false,
            },
            {
              name: "clientPhone",
              type: "phone",
              label: "Phone Number",
              required: false,
              prefilledByAdmin: false,
            },
            {
              name: "clientAddress",
              type: "address",
              label: "Address",
              required: true,
              prefilledByAdmin: false,
            },
          ],
        },
      ],
    },
  },

  // ============================================================
  // CREW TEMPLATES
  // ============================================================

  // 9. Crew Deal Memo
  {
    name: "Crew Deal Memo",
    slug: "crew-deal-memo",
    category: "CREW",
    description:
      "Standard deal memo outlining the terms of engagement for a crew member, including rate, dates, and role details.",
    requiresSignature: true,
    isExternal: true,
    fieldSchema: {
      sections: [
        {
          title: "Production Details",
          description: undefined,
          fields: [
            {
              name: "projectName",
              type: "text",
              label: "Project Name",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "productionCompany",
              type: "text",
              label: "Production Company",
              required: true,
              prefilledByAdmin: true,
              defaultValue: "Geared Like A Machine LLC",
            },
            {
              name: "role",
              type: "text",
              label: "Role / Position",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "department",
              type: "select",
              label: "Department",
              required: true,
              prefilledByAdmin: true,
              options: [
                { label: "Camera", value: "camera" },
                { label: "Grip & Electric", value: "grip_electric" },
                { label: "Sound", value: "sound" },
                { label: "Art", value: "art" },
                { label: "Wardrobe / HMU", value: "wardrobe_hmu" },
                { label: "Production", value: "production" },
                { label: "Post-Production", value: "post" },
                { label: "Direction", value: "direction" },
                { label: "Other", value: "other" },
              ],
            },
            {
              name: "shootDates",
              type: "dateRange",
              label: "Shoot Dates",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "dayRate",
              type: "currency",
              label: "Day Rate",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "kitFee",
              type: "currency",
              label: "Kit Fee",
              required: false,
              prefilledByAdmin: true,
            },
            {
              name: "overtimeRate",
              type: "text",
              label: "Overtime Rate",
              required: true,
              prefilledByAdmin: true,
              defaultValue: "1.5x after 10 hours",
            },
            {
              name: "perDiem",
              type: "currency",
              label: "Per Diem",
              required: false,
              prefilledByAdmin: true,
            },
            {
              name: "travelProvided",
              type: "checkbox",
              label: "Travel provided by production",
              required: false,
              prefilledByAdmin: true,
            },
            {
              name: "additionalTerms",
              type: "textarea",
              label: "Additional Terms",
              required: false,
              prefilledByAdmin: true,
            },
          ],
        },
        {
          title: "Crew Member Information",
          description: undefined,
          fields: [
            {
              name: "crewMemberName",
              type: "text",
              label: "Full Legal Name",
              required: true,
              prefilledByAdmin: false,
            },
            {
              name: "crewMemberAddress",
              type: "address",
              label: "Address",
              required: true,
              prefilledByAdmin: false,
            },
            {
              name: "crewMemberPhone",
              type: "phone",
              label: "Phone Number",
              required: true,
              prefilledByAdmin: false,
            },
            {
              name: "crewMemberEmail",
              type: "email",
              label: "Email Address",
              required: true,
              prefilledByAdmin: false,
            },
            {
              name: "ssnLast4",
              type: "text",
              label: "Last 4 of SSN",
              required: true,
              prefilledByAdmin: false,
              helpText: "For 1099 reporting purposes only",
            },
            {
              name: "emergencyContactName",
              type: "text",
              label: "Emergency Contact Name",
              required: true,
              prefilledByAdmin: false,
            },
            {
              name: "emergencyContactPhone",
              type: "phone",
              label: "Emergency Contact Phone",
              required: true,
              prefilledByAdmin: false,
            },
            {
              name: "w9Acknowledgment",
              type: "checkbox",
              label: "I will provide a completed W-9 form",
              required: true,
              prefilledByAdmin: false,
            },
          ],
        },
      ],
    },
  },

  // 10. Crew Invoice
  {
    name: "Crew Invoice",
    slug: "crew-invoice",
    category: "CREW",
    description:
      "Invoice sent to crew members summarizing payment for completed work, with options to select preferred payment method.",
    requiresSignature: false,
    isExternal: true,
    fieldSchema: {
      sections: [
        {
          title: "Payment Summary",
          description:
            "Review the details of your work and payment below",
          fields: [
            {
              name: "projectName",
              type: "text",
              label: "Project Name",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "crewMemberName",
              type: "text",
              label: "Crew Member Name",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "role",
              type: "text",
              label: "Role",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "workDates",
              type: "dateRange",
              label: "Work Dates",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "daysWorked",
              type: "number",
              label: "Days Worked",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "dayRate",
              type: "currency",
              label: "Day Rate",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "kitFee",
              type: "currency",
              label: "Kit Fee",
              required: false,
              prefilledByAdmin: true,
            },
            {
              name: "overtimeHours",
              type: "number",
              label: "Overtime Hours",
              required: false,
              prefilledByAdmin: true,
            },
            {
              name: "overtimeAmount",
              type: "currency",
              label: "Overtime Amount",
              required: false,
              prefilledByAdmin: true,
            },
            {
              name: "perDiemTotal",
              type: "currency",
              label: "Per Diem Total",
              required: false,
              prefilledByAdmin: true,
            },
            {
              name: "mileageReimbursement",
              type: "currency",
              label: "Mileage Reimbursement",
              required: false,
              prefilledByAdmin: true,
            },
            {
              name: "totalPayment",
              type: "currency",
              label: "Total Payment",
              required: true,
              prefilledByAdmin: true,
            },
          ],
        },
        {
          title: "Payment Preferences",
          description:
            "Select how you would like to receive payment",
          fields: [
            {
              name: "paymentMethod",
              type: "select",
              label: "Preferred Payment Method",
              required: true,
              prefilledByAdmin: false,
              options: [
                { label: "ACH (Direct Deposit)", value: "ACH" },
                { label: "Zelle", value: "ZELLE" },
                { label: "Check", value: "CHECK" },
                { label: "Wire Transfer", value: "WIRE" },
                { label: "PayPal", value: "PAYPAL" },
                { label: "Venmo", value: "VENMO" },
              ],
            },
            {
              name: "achRoutingNumber",
              type: "text",
              label: "ACH Routing Number",
              required: false,
              prefilledByAdmin: false,
              helpText: "Required for ACH",
            },
            {
              name: "achAccountNumber",
              type: "text",
              label: "ACH Account Number",
              required: false,
              prefilledByAdmin: false,
            },
            {
              name: "achAccountType",
              type: "select",
              label: "ACH Account Type",
              required: false,
              prefilledByAdmin: false,
              options: [
                { label: "Checking", value: "checking" },
                { label: "Savings", value: "savings" },
              ],
            },
            {
              name: "zelleEmail",
              type: "email",
              label: "Zelle Email",
              required: false,
              prefilledByAdmin: false,
            },
            {
              name: "checkMailingAddress",
              type: "address",
              label: "Check Mailing Address",
              required: false,
              prefilledByAdmin: false,
            },
            {
              name: "wireRoutingNumber",
              type: "text",
              label: "Wire Routing Number",
              required: false,
              prefilledByAdmin: false,
            },
            {
              name: "wireAccountNumber",
              type: "text",
              label: "Wire Account Number",
              required: false,
              prefilledByAdmin: false,
            },
            {
              name: "wireBankName",
              type: "text",
              label: "Wire Bank Name",
              required: false,
              prefilledByAdmin: false,
            },
            {
              name: "paypalEmail",
              type: "email",
              label: "PayPal Email",
              required: false,
              prefilledByAdmin: false,
            },
            {
              name: "venmoHandle",
              type: "text",
              label: "Venmo Handle",
              required: false,
              prefilledByAdmin: false,
            },
            {
              name: "notes",
              type: "textarea",
              label: "Notes",
              required: false,
              prefilledByAdmin: false,
            },
          ],
        },
      ],
    },
  },

  // ============================================================
  // PRODUCTION TEMPLATES
  // ============================================================

  // 11. Call Sheet
  {
    name: "Call Sheet",
    slug: "call-sheet",
    category: "PRODUCTION",
    description:
      "Daily call sheet with production info, location details, weather, and schedule for cast and crew.",
    requiresSignature: false,
    isExternal: false,
    fieldSchema: {
      sections: [
        {
          title: "Production Info",
          description: undefined,
          fields: [
            {
              name: "projectName",
              type: "text",
              label: "Project Name",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "shootDate",
              type: "date",
              label: "Shoot Date",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "dayNumber",
              type: "text",
              label: "Day Number",
              required: true,
              prefilledByAdmin: true,
              placeholder: "e.g. Day 1 of 3",
            },
            {
              name: "generalCallTime",
              type: "text",
              label: "General Call Time",
              required: true,
              prefilledByAdmin: true,
              placeholder: "e.g. 6:00 AM",
            },
            {
              name: "estimatedWrap",
              type: "text",
              label: "Estimated Wrap",
              required: true,
              prefilledByAdmin: true,
              placeholder: "e.g. 6:00 PM",
            },
          ],
        },
        {
          title: "Location",
          description: undefined,
          fields: [
            {
              name: "locationName",
              type: "text",
              label: "Location Name",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "locationAddress",
              type: "text",
              label: "Location Address",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "parkingNotes",
              type: "textarea",
              label: "Parking Notes",
              required: false,
              prefilledByAdmin: true,
            },
            {
              name: "nearestHospital",
              type: "text",
              label: "Nearest Hospital",
              required: true,
              prefilledByAdmin: true,
            },
          ],
        },
        {
          title: "Weather",
          description: undefined,
          fields: [
            {
              name: "weatherSummary",
              type: "text",
              label: "Weather Summary",
              required: true,
              prefilledByAdmin: true,
              placeholder: "e.g. Partly cloudy, 10% chance of rain",
            },
            {
              name: "temperature",
              type: "text",
              label: "Temperature",
              required: true,
              prefilledByAdmin: true,
              placeholder: "e.g. High 85F / Low 68F",
            },
            {
              name: "sunrise",
              type: "text",
              label: "Sunrise",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "sunset",
              type: "text",
              label: "Sunset",
              required: true,
              prefilledByAdmin: true,
            },
          ],
        },
        {
          title: "Schedule & Notes",
          description: undefined,
          fields: [
            {
              name: "schedule",
              type: "textarea",
              label: "Schedule",
              required: true,
              prefilledByAdmin: true,
              placeholder:
                "Detailed schedule with times and activities",
            },
            {
              name: "generalNotes",
              type: "textarea",
              label: "General Notes",
              required: false,
              prefilledByAdmin: true,
            },
            {
              name: "specialInstructions",
              type: "textarea",
              label: "Special Instructions",
              required: false,
              prefilledByAdmin: true,
            },
          ],
        },
      ],
    },
  },

  // 12. Shot List
  {
    name: "Shot List",
    slug: "shot-list",
    category: "PRODUCTION",
    description:
      "Organized list of planned shots for a scene or shoot day, including shot details, angles, and notes.",
    requiresSignature: false,
    isExternal: false,
    fieldSchema: {
      sections: [
        {
          title: "Shot List Details",
          description: undefined,
          fields: [
            {
              name: "projectName",
              type: "text",
              label: "Project Name",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "sceneNumber",
              type: "text",
              label: "Scene Number",
              required: false,
              prefilledByAdmin: true,
            },
            {
              name: "shootDate",
              type: "date",
              label: "Shoot Date",
              required: false,
              prefilledByAdmin: true,
            },
            {
              name: "director",
              type: "text",
              label: "Director",
              required: false,
              prefilledByAdmin: true,
            },
            {
              name: "dp",
              type: "text",
              label: "Director of Photography",
              required: false,
              prefilledByAdmin: true,
            },
            {
              name: "description",
              type: "textarea",
              label: "Scene Description",
              required: false,
              prefilledByAdmin: true,
            },
            {
              name: "notes",
              type: "textarea",
              label: "Notes",
              required: false,
              prefilledByAdmin: true,
            },
          ],
        },
      ],
    },
  },

  // 13. Change Order
  {
    name: "Change Order",
    slug: "change-order",
    category: "PRODUCTION",
    description:
      "Formal change request documenting scope changes, cost impacts, and timeline adjustments requiring client approval.",
    requiresSignature: true,
    isExternal: true,
    fieldSchema: {
      sections: [
        {
          title: "Change Order Details",
          description: undefined,
          fields: [
            {
              name: "projectName",
              type: "text",
              label: "Project Name",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "changeOrderNumber",
              type: "text",
              label: "Change Order Number",
              required: true,
              prefilledByAdmin: true,
              placeholder: "e.g. CO-001",
            },
            {
              name: "dateIssued",
              type: "date",
              label: "Date Issued",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "changeDescription",
              type: "textarea",
              label: "Description of Change",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "reason",
              type: "textarea",
              label: "Reason for Change",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "costImpact",
              type: "currency",
              label: "Cost Impact",
              required: true,
              prefilledByAdmin: true,
              helpText:
                "Additional cost resulting from this change",
            },
            {
              name: "timelineImpact",
              type: "text",
              label: "Timeline Impact",
              required: false,
              prefilledByAdmin: true,
              placeholder: "e.g. +2 days to delivery schedule",
            },
            {
              name: "deliverableImpact",
              type: "textarea",
              label: "Deliverable Impact",
              required: false,
              prefilledByAdmin: true,
            },
          ],
        },
        {
          title: "Client Approval",
          description: undefined,
          fields: [
            {
              name: "approverName",
              type: "text",
              label: "Approver Name",
              required: true,
              prefilledByAdmin: false,
            },
            {
              name: "approverTitle",
              type: "text",
              label: "Approver Title",
              required: false,
              prefilledByAdmin: false,
            },
            {
              name: "approvalNotes",
              type: "textarea",
              label: "Approval Notes",
              required: false,
              prefilledByAdmin: false,
            },
          ],
        },
      ],
    },
  },

  // 14. Incident Report
  {
    name: "Incident Report",
    slug: "incident-report",
    category: "PRODUCTION",
    description:
      "Report documenting any safety incident or near-miss on set, including severity, people involved, and corrective actions.",
    requiresSignature: false,
    isExternal: false,
    fieldSchema: {
      sections: [
        {
          title: "Incident Details",
          description: undefined,
          fields: [
            {
              name: "projectName",
              type: "text",
              label: "Project Name",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "incidentDate",
              type: "date",
              label: "Incident Date",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "incidentTime",
              type: "text",
              label: "Incident Time",
              required: true,
              prefilledByAdmin: true,
              placeholder: "e.g. 2:30 PM",
            },
            {
              name: "location",
              type: "text",
              label: "Location",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "severity",
              type: "select",
              label: "Severity",
              required: true,
              prefilledByAdmin: true,
              options: [
                { label: "Near Miss", value: "near_miss" },
                { label: "Minor", value: "minor" },
                { label: "Moderate", value: "moderate" },
                { label: "Severe", value: "severe" },
              ],
            },
            {
              name: "description",
              type: "textarea",
              label: "Incident Description",
              required: true,
              prefilledByAdmin: true,
              placeholder:
                "Detailed description of what happened",
            },
          ],
        },
        {
          title: "People Involved",
          description: undefined,
          fields: [
            {
              name: "injuredPerson",
              type: "text",
              label: "Injured Person",
              required: false,
              prefilledByAdmin: true,
            },
            {
              name: "injuryDescription",
              type: "textarea",
              label: "Injury Description",
              required: false,
              prefilledByAdmin: true,
            },
            {
              name: "treatmentProvided",
              type: "textarea",
              label: "Treatment Provided",
              required: false,
              prefilledByAdmin: true,
            },
            {
              name: "witnesses",
              type: "textarea",
              label: "Witnesses",
              required: false,
              prefilledByAdmin: true,
              placeholder: "Names and contact information of witnesses",
            },
          ],
        },
        {
          title: "Follow-Up",
          description: undefined,
          fields: [
            {
              name: "rootCause",
              type: "textarea",
              label: "Root Cause",
              required: false,
              prefilledByAdmin: true,
            },
            {
              name: "correctiveActions",
              type: "textarea",
              label: "Corrective Actions",
              required: false,
              prefilledByAdmin: true,
            },
            {
              name: "preventionMeasures",
              type: "textarea",
              label: "Prevention Measures",
              required: false,
              prefilledByAdmin: true,
            },
            {
              name: "reportedBy",
              type: "text",
              label: "Reported By",
              required: true,
              prefilledByAdmin: true,
            },
          ],
        },
      ],
    },
  },

  // 15. Safety Briefing Checklist
  {
    name: "Safety Briefing Checklist",
    slug: "safety-briefing-checklist",
    category: "PRODUCTION",
    description:
      "Pre-shoot safety briefing checklist covering emergency exits, first aid, hazards, and PPE requirements.",
    requiresSignature: false,
    isExternal: false,
    fieldSchema: {
      sections: [
        {
          title: "Briefing Details",
          description: undefined,
          fields: [
            {
              name: "projectName",
              type: "text",
              label: "Project Name",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "date",
              type: "date",
              label: "Date",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "location",
              type: "text",
              label: "Location",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "safetyOfficer",
              type: "text",
              label: "Safety Officer",
              required: true,
              prefilledByAdmin: true,
            },
          ],
        },
        {
          title: "Safety Items Covered",
          description: undefined,
          fields: [
            {
              name: "safetyItems",
              type: "checkboxGroup",
              label: "Safety Items Covered",
              required: true,
              prefilledByAdmin: true,
              options: [
                { label: "Emergency Exits", value: "exits" },
                { label: "First Aid Kit Location", value: "first_aid" },
                { label: "Nearest Hospital", value: "hospital" },
                { label: "Fire Extinguisher Location", value: "fire_extinguisher" },
                { label: "PPE Requirements", value: "ppe" },
                { label: "Heat / Cold Safety", value: "heat_safety" },
                { label: "Stunts / Special Effects", value: "stunts" },
                { label: "Electrical Safety", value: "electrical" },
                { label: "Vehicle Safety", value: "vehicles" },
                { label: "Hazardous Materials", value: "hazmat" },
              ],
            },
            {
              name: "additionalHazards",
              type: "textarea",
              label: "Additional Hazards",
              required: false,
              prefilledByAdmin: true,
              placeholder: "Any location-specific or production-specific hazards",
            },
            {
              name: "notes",
              type: "textarea",
              label: "Notes",
              required: false,
              prefilledByAdmin: true,
            },
          ],
        },
      ],
    },
  },

  // ============================================================
  // FINANCIAL TEMPLATES
  // ============================================================

  // 16. Client Invoice
  {
    name: "Client Invoice",
    slug: "client-invoice",
    category: "FINANCIAL",
    description:
      "Professional invoice for client billing, including line items, taxes, payment terms, and accepted payment methods.",
    requiresSignature: false,
    isExternal: false,
    fieldSchema: {
      sections: [
        {
          title: "Invoice Details",
          description: undefined,
          fields: [
            {
              name: "invoiceNumber",
              type: "text",
              label: "Invoice Number",
              required: true,
              prefilledByAdmin: true,
              placeholder: "e.g. GLM-2026-001",
            },
            {
              name: "invoiceDate",
              type: "date",
              label: "Invoice Date",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "dueDate",
              type: "date",
              label: "Due Date",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "projectName",
              type: "text",
              label: "Project Name",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "poNumber",
              type: "text",
              label: "PO Number",
              required: false,
              prefilledByAdmin: true,
            },
          ],
        },
        {
          title: "Client Info",
          description: undefined,
          fields: [
            {
              name: "clientName",
              type: "text",
              label: "Client Name",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "clientCompany",
              type: "text",
              label: "Client Company",
              required: false,
              prefilledByAdmin: true,
            },
            {
              name: "clientAddress",
              type: "address",
              label: "Client Address",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "clientEmail",
              type: "email",
              label: "Client Email",
              required: false,
              prefilledByAdmin: true,
            },
          ],
        },
        {
          title: "Line Items",
          description: undefined,
          fields: [
            {
              name: "lineItems",
              type: "textarea",
              label: "Line Items",
              required: true,
              prefilledByAdmin: true,
              placeholder:
                "Description | Quantity | Rate | Amount (one per line)",
            },
            {
              name: "subtotal",
              type: "currency",
              label: "Subtotal",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "discount",
              type: "currency",
              label: "Discount",
              required: false,
              prefilledByAdmin: true,
            },
            {
              name: "salesTax",
              type: "currency",
              label: "Sales Tax",
              required: false,
              prefilledByAdmin: true,
            },
            {
              name: "totalDue",
              type: "currency",
              label: "Total Due",
              required: true,
              prefilledByAdmin: true,
            },
          ],
        },
        {
          title: "Payment Info",
          description: undefined,
          fields: [
            {
              name: "paymentTerms",
              type: "select",
              label: "Payment Terms",
              required: true,
              prefilledByAdmin: true,
              options: [
                { label: "Due on Receipt", value: "due_on_receipt" },
                { label: "Net 15", value: "net_15" },
                { label: "Net 30", value: "net_30" },
                { label: "Net 45", value: "net_45" },
                { label: "Net 60", value: "net_60" },
              ],
            },
            {
              name: "paymentMethods",
              type: "textarea",
              label: "Accepted Payment Methods",
              required: true,
              prefilledByAdmin: true,
              defaultValue:
                "ACH / Direct Deposit\nZelle\nCheck (payable to Geared Like A Machine LLC)\nWire Transfer",
            },
            {
              name: "notes",
              type: "textarea",
              label: "Notes",
              required: false,
              prefilledByAdmin: true,
            },
          ],
        },
      ],
    },
  },

  // 17. Estimate
  {
    name: "Estimate",
    slug: "estimate",
    category: "FINANCIAL",
    description:
      "Three-tier pricing estimate (Good/Better/Best) for prospective clients, with project details and payment terms.",
    requiresSignature: false,
    isExternal: false,
    fieldSchema: {
      sections: [
        {
          title: "Estimate Details",
          description: undefined,
          fields: [
            {
              name: "estimateNumber",
              type: "text",
              label: "Estimate Number",
              required: true,
              prefilledByAdmin: true,
              placeholder: "e.g. EST-2026-001",
            },
            {
              name: "estimateDate",
              type: "date",
              label: "Estimate Date",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "validUntil",
              type: "date",
              label: "Valid Until",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "projectName",
              type: "text",
              label: "Project Name",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "projectDescription",
              type: "textarea",
              label: "Project Description",
              required: true,
              prefilledByAdmin: true,
            },
          ],
        },
        {
          title: "Client Info",
          description: undefined,
          fields: [
            {
              name: "clientName",
              type: "text",
              label: "Client Name",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "clientCompany",
              type: "text",
              label: "Client Company",
              required: false,
              prefilledByAdmin: true,
            },
            {
              name: "clientEmail",
              type: "email",
              label: "Client Email",
              required: false,
              prefilledByAdmin: true,
            },
          ],
        },
        {
          title: "Pricing Tiers",
          description: undefined,
          fields: [
            {
              name: "goodTierName",
              type: "text",
              label: "Good Tier Name",
              required: true,
              prefilledByAdmin: true,
              defaultValue: "Essential",
            },
            {
              name: "goodTierDescription",
              type: "textarea",
              label: "Good Tier Description",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "goodTierPrice",
              type: "currency",
              label: "Good Tier Price",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "betterTierName",
              type: "text",
              label: "Better Tier Name",
              required: true,
              prefilledByAdmin: true,
              defaultValue: "Professional",
            },
            {
              name: "betterTierDescription",
              type: "textarea",
              label: "Better Tier Description",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "betterTierPrice",
              type: "currency",
              label: "Better Tier Price",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "bestTierName",
              type: "text",
              label: "Best Tier Name",
              required: true,
              prefilledByAdmin: true,
              defaultValue: "Premium",
            },
            {
              name: "bestTierDescription",
              type: "textarea",
              label: "Best Tier Description",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "bestTierPrice",
              type: "currency",
              label: "Best Tier Price",
              required: true,
              prefilledByAdmin: true,
            },
          ],
        },
        {
          title: "Terms",
          description: undefined,
          fields: [
            {
              name: "paymentTerms",
              type: "textarea",
              label: "Payment Terms",
              required: true,
              prefilledByAdmin: true,
              defaultValue:
                "50% deposit upon approval, 25% upon completion of production, 25% upon final delivery.",
            },
            {
              name: "notes",
              type: "textarea",
              label: "Notes",
              required: false,
              prefilledByAdmin: true,
            },
          ],
        },
      ],
    },
  },

  // 18. Production Budget
  {
    name: "Production Budget",
    slug: "production-budget",
    category: "FINANCIAL",
    description:
      "Detailed production budget broken down by department, with production fee, contingency, and grand total calculations.",
    requiresSignature: false,
    isExternal: false,
    fieldSchema: {
      sections: [
        {
          title: "Budget Overview",
          description: undefined,
          fields: [
            {
              name: "projectName",
              type: "text",
              label: "Project Name",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "clientName",
              type: "text",
              label: "Client Name",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "budgetDate",
              type: "date",
              label: "Budget Date",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "budgetVersion",
              type: "text",
              label: "Budget Version",
              required: true,
              prefilledByAdmin: true,
              defaultValue: "v1",
            },
            {
              name: "preparedBy",
              type: "text",
              label: "Prepared By",
              required: true,
              prefilledByAdmin: true,
            },
          ],
        },
        {
          title: "Budget Line Items",
          description: undefined,
          fields: [
            {
              name: "preProduction",
              type: "currency",
              label: "Pre-Production",
              required: false,
              prefilledByAdmin: true,
            },
            {
              name: "crew",
              type: "currency",
              label: "Crew",
              required: false,
              prefilledByAdmin: true,
            },
            {
              name: "talent",
              type: "currency",
              label: "Talent",
              required: false,
              prefilledByAdmin: true,
            },
            {
              name: "equipment",
              type: "currency",
              label: "Equipment",
              required: false,
              prefilledByAdmin: true,
            },
            {
              name: "locations",
              type: "currency",
              label: "Locations",
              required: false,
              prefilledByAdmin: true,
            },
            {
              name: "travel",
              type: "currency",
              label: "Travel",
              required: false,
              prefilledByAdmin: true,
            },
            {
              name: "artDepartment",
              type: "currency",
              label: "Art Department",
              required: false,
              prefilledByAdmin: true,
            },
            {
              name: "postProduction",
              type: "currency",
              label: "Post-Production",
              required: false,
              prefilledByAdmin: true,
            },
            {
              name: "music",
              type: "currency",
              label: "Music",
              required: false,
              prefilledByAdmin: true,
            },
            {
              name: "insurance",
              type: "currency",
              label: "Insurance",
              required: false,
              prefilledByAdmin: true,
            },
            {
              name: "miscellaneous",
              type: "currency",
              label: "Miscellaneous",
              required: false,
              prefilledByAdmin: true,
            },
          ],
        },
        {
          title: "Totals",
          description: undefined,
          fields: [
            {
              name: "subtotal",
              type: "currency",
              label: "Subtotal",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "productionFeePercent",
              type: "number",
              label: "Production Fee %",
              required: true,
              prefilledByAdmin: true,
              defaultValue: 22,
            },
            {
              name: "productionFee",
              type: "currency",
              label: "Production Fee",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "contingencyPercent",
              type: "number",
              label: "Contingency %",
              required: true,
              prefilledByAdmin: true,
              defaultValue: 10,
            },
            {
              name: "contingency",
              type: "currency",
              label: "Contingency",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "grandTotal",
              type: "currency",
              label: "Grand Total",
              required: true,
              prefilledByAdmin: true,
            },
            {
              name: "notes",
              type: "textarea",
              label: "Notes",
              required: false,
              prefilledByAdmin: true,
            },
          ],
        },
      ],
    },
  },
];
