export type InventoryItem = {
  id: number;
  category: string;
  item: string;
  rate: number;
};

export const categories = [
  "Audio",
  "Camera",
  "Drone",
  "Grip Van",
  "Lenses",
  "Lighting",
  "Media",
  "Monitoring",
  "Power",
  "Support",
] as const;

export const inventory: InventoryItem[] = [
  // ── Audio ──
  { id: 1, category: "Audio", item: "ATian Microphone Metal Boom Pole Holder / Audio Boom Cradle Mount Stand", rate: 8 },
  { id: 2, category: "Audio", item: "DJI Mic 2 Camera Adapter", rate: 8 },
  { id: 3, category: "Audio", item: "DJI Mic 2 Kit", rate: 30 },
  { id: 4, category: "Audio", item: "Hollyland Lark M2S Combo Wireless Lavalier System (Camera RX + USB-C + Lightning)", rate: 25 },
  { id: 5, category: "Audio", item: "Hollyland Solidcom C1 Pro Headsets (x4)", rate: 80 },
  { id: 6, category: "Audio", item: "LyxPro MPL-20 Portable Mic Boom Pole (Internal XLR)", rate: 12 },
  { id: 7, category: "Audio", item: "Rode Wireless Pro Kit", rate: 30 },
  { id: 8, category: "Audio", item: "Sennheiser AVX-ME2 Lav Set", rate: 45 },
  { id: 9, category: "Audio", item: "Sennheiser MKE 600 Shotgun", rate: 30 },
  { id: 10, category: "Audio", item: "Zoom H6 Field Kit", rate: 35 },

  // ── Camera ──
  { id: 11, category: "Camera", item: "DJI Osmo Action 5 Pro Adventure Combo", rate: 40 },
  { id: 12, category: "Camera", item: "Nikon ZR Package", rate: 250 },
  { id: 13, category: "Camera", item: "RED Komodo-X 6K Package", rate: 450 },
  { id: 14, category: "Camera", item: "RED V-Raptor (X) VV 8K Package", rate: 650 },
  { id: 15, category: "Camera", item: "Sony FX3 Package (x2)", rate: 200 },

  // ── Drone ──
  { id: 16, category: "Drone", item: "DJI Avata 2 Fly More Combo (3 Batteries)", rate: 150 },
  { id: 17, category: "Drone", item: "DJI Inspire 3 Dual-Op Team", rate: 2200 },
  { id: 18, category: "Drone", item: "DJI Mavic 4 PRO Fly More Combo (6K60 HDR, 100MP, ActiveTrack 360)", rate: 200 },
  { id: 19, category: "Drone", item: "GEPRC Vapor-D5 HD O4 Pro FPV Drone (ELRS 2.4G, GPS)", rate: 150 },
  { id: 20, category: "Drone", item: "K&F Concept ND/PL Filter Set for DJI Mavic 4 Pro (ND8/16/32/64)", rate: 15 },

  // ── Grip Van ──
  { id: 21, category: "Grip Van", item: "1-Ton Grip Van", rate: 350 },
  { id: 22, category: "Grip Van", item: "12x12 Frames + Solids + 1/2 Grid", rate: 175 },
  { id: 23, category: "Grip Van", item: "24x36 Frames + Net/Silk/Solid Fabrics", rate: 50 },
  { id: 24, category: "Grip Van", item: "4x4 Package: Floppies, Solids, Art Silk, Frost, Grid, Bead Board", rate: 175 },
  { id: 25, category: "Grip Van", item: "6x6 Frame + Multiple Textiles", rate: 100 },
  { id: 26, category: "Grip Van", item: "8x8 Frames + Magic Cloth / Muslin / Grids / Bounce / Solids", rate: 145 },
  { id: 27, category: "Grip Van", item: "Apple Box Sets", rate: 10 },
  { id: 28, category: "Grip Van", item: "Baby Pins / Studs / Threaded Adapters", rate: 25 },
  { id: 29, category: "Grip Van", item: "Big Ben Clamps, Right-Angle Clamps, Scissor Clamps", rate: 35 },
  { id: 30, category: "Grip Van", item: "C-Stands: 40\" (x10), 20\" (x2)", rate: 150 },
  { id: 31, category: "Grip Van", item: "Expendables: Duvetyne, Muslin, Cinefoil, Tape, Gels, Visqueen, Paracord, Cones", rate: 200 },
  { id: 32, category: "Grip Van", item: "High Roller Triple Risers", rate: 75 },
  { id: 33, category: "Grip Van", item: "Impact SSB-10 Saddle Shot Bag 10 lb (x4)", rate: 15 },
  { id: 34, category: "Grip Van", item: "Junior Roller Double Risers", rate: 60 },
  { id: 35, category: "Grip Van", item: "Junior Slider Stands", rate: 35 },
  { id: 36, category: "Grip Van", item: "Kupo 3.5in Extra Long 5/8in Baby Stud with 3/8in-16 Male Thread (x2)", rate: 8 },
  { id: 37, category: "Grip Van", item: "Kupo Butterfly Frame Kit 12x12", rate: 100 },
  { id: 38, category: "Grip Van", item: "Matthellini Clamps, Maffers, End Jaws", rate: 35 },
  { id: 39, category: "Grip Van", item: "Matthews 12x12 Overhead Fabric Solid Black", rate: 75 },
  { id: 40, category: "Grip Van", item: "Matthews BH-20 Ball Head", rate: 15 },
  { id: 41, category: "Grip Van", item: "Matthews Baby Ballhead Adapter (x2)", rate: 10 },
  { id: 42, category: "Grip Van", item: "Matthews Quick Reverse Ear for 1in Square Tube (x2)", rate: 10 },
  { id: 43, category: "Grip Van", item: "Matthews Silent Gridcloth Lite Fabric 12x12", rate: 75 },
  { id: 44, category: "Grip Van", item: "Matthews Combo Stands (11')", rate: 75 },
  { id: 45, category: "Grip Van", item: "Menace Arm + Junior/Mini Booms", rate: 65 },
  { id: 46, category: "Grip Van", item: "PROAIM SnapRig Baby Pin Set with 3/8in Male/Female Threads", rate: 8 },
  { id: 47, category: "Grip Van", item: "Sky-Hi Baby Stands (13.5')", rate: 45 },
  { id: 48, category: "Grip Van", item: "Speed Rail + Square Stock System", rate: 65 },
  { id: 49, category: "Grip Van", item: "Sprinter Cargo Van (144WB, Loading Ramp)", rate: 250 },

  // ── Lenses ──
  { id: 50, category: "Lenses", item: "82mm Close-Up Macro Filter Kit (+1,+2,+4,+10)", rate: 12 },
  { id: 51, category: "Lenses", item: "BLAZAR Remus 33mm T1.8 1.5x Full-Frame Anamorphic (ARRI PL, Silver Flare)", rate: 55 },
  { id: 52, category: "Lenses", item: "DZOFilm PL Set: 12 / 16 / 25 / 35 / 50 / 75 / 100 / 125", rate: 500 },
  { id: 53, category: "Lenses", item: "DZOFilm Tango 18-90mm T2.9", rate: 175 },
  { id: 54, category: "Lenses", item: "Laowa 12mm T2.9 Zero-D Cine", rate: 65 },
  { id: 55, category: "Lenses", item: "NEEWER 4x5.65 Square UV Cinema Protective Filter", rate: 10 },
  { id: 56, category: "Lenses", item: "NiSi Swift 77mm IR/UV Cut Filter (Press-On)", rate: 8 },
  { id: 57, category: "Lenses", item: "NiSi Swift 82mm IR/UV Cut Filter (Press-On)", rate: 8 },
  { id: 58, category: "Lenses", item: "Nikon NIKKOR Z 135mm f/1.8 S Plena", rate: 75 },
  { id: 59, category: "Lenses", item: "Nikon NIKKOR Z 24-70mm f/2.8 S", rate: 55 },
  { id: 60, category: "Lenses", item: "Nikon NIKKOR Z 24-70mm f/2.8 S II", rate: 60 },
  { id: 61, category: "Lenses", item: "Remus 1.5x Anamorphic Set: 45 / 65 / 100", rate: 165 },
  { id: 62, category: "Lenses", item: "Sigma High Speed Zoom 18-35mm T2", rate: 125 },
  { id: 63, category: "Lenses", item: "Sigma High Speed Zoom 50-100mm T2", rate: 125 },
  { id: 64, category: "Lenses", item: "Sony AF Set: 70-200 2.8, 24-105 (x2), 16-35 2.8 GM, 24-70 2.8", rate: 225 },
  { id: 65, category: "Lenses", item: "Sony FE 16-35mm F2.8 GM II", rate: 55 },
  { id: 66, category: "Lenses", item: "Voigtlander Heliar-Hyper Wide 10mm f/5.6 Aspherical (Leica M)", rate: 35 },
  { id: 67, category: "Lenses", item: "Voigtlander ULTRON Vintage Line 28mm F2.0 Aspherical VM Type II", rate: 30 },

  // ── Lighting ──
  { id: 68, category: "Lighting", item: "3' Dome Softbox + Grid", rate: 20 },
  { id: 69, category: "Lighting", item: "5' Dome Softbox + Grid", rate: 25 },
  { id: 70, category: "Lighting", item: "Amaran 150c", rate: 35 },
  { id: 71, category: "Lighting", item: "Amaran 300c", rate: 50 },
  { id: 72, category: "Lighting", item: "Amaran F22c", rate: 45 },
  { id: 73, category: "Lighting", item: "Amaran Spotlight SE 19deg (x2)", rate: 20 },
  { id: 74, category: "Lighting", item: "Amaran T2c Tube Lights (x2)", rate: 25 },
  { id: 75, category: "Lighting", item: "Aputure Accent B7c (x4)", rate: 40 },
  { id: 76, category: "Lighting", item: "Aputure CF12 Fresnel for STORM 1000c/1200x", rate: 20 },
  { id: 77, category: "Lighting", item: "Aputure CF7 Fresnel and Barn Doors Kit for Storm 400x", rate: 20 },
  { id: 78, category: "Lighting", item: "Aputure F10 Barndoors (x3)", rate: 10 },
  { id: 79, category: "Lighting", item: "Aputure Fresnel 2X", rate: 15 },
  { id: 80, category: "Lighting", item: "Aputure LS 1200d Pro", rate: 200 },
  { id: 81, category: "Lighting", item: "Aputure LS 600c Pro", rate: 150 },
  { id: 82, category: "Lighting", item: "Aputure LS 600d Pro (x2)", rate: 250 },
  { id: 83, category: "Lighting", item: "Aputure Light Dome 150 Softbox (5 ft)", rate: 30 },
  { id: 84, category: "Lighting", item: "Aputure MC Pro Kit (8-Light)", rate: 85 },
  { id: 85, category: "Lighting", item: "Aputure Nova P300c", rate: 55 },
  { id: 86, category: "Lighting", item: "Aputure Nova Softbox Kit", rate: 25 },
  { id: 87, category: "Lighting", item: "Aputure STORM 1200X", rate: 250 },
  { id: 88, category: "Lighting", item: "Aputure STORM 1200x Reflector Kit (15deg Narrow + 30deg Medium)", rate: 25 },
  { id: 89, category: "Lighting", item: "Aputure STORM 400X", rate: 135 },
  { id: 90, category: "Lighting", item: "Aputure STORM 80c + CF4 Fresnel", rate: 75 },
  { id: 91, category: "Lighting", item: "Aputure STORM 80c Portable 3-Light Kit (Hyper Reflector + Lantern + Protection Cover)", rate: 110 },
  { id: 92, category: "Lighting", item: "Aputure Spotlight 26deg + Gobo Kit", rate: 55 },
  { id: 93, category: "Lighting", item: "Aputure Spotlight Mini 36deg Lens Kit", rate: 15 },
  { id: 94, category: "Lighting", item: "Aputure Lantern", rate: 10 },
  { id: 95, category: "Lighting", item: "Arri Tungsten Kit (1K / 650 / 300 / 150)", rate: 120 },
  { id: 96, category: "Lighting", item: "CHAUVET DJ Hurricane Haze 4D", rate: 40 },
  { id: 97, category: "Lighting", item: "Godox KNOWLED F600Bi Mats (x2) + Full Accessories", rate: 250 },
  { id: 98, category: "Lighting", item: "Lightbridge CRLS C-Drive+ Kit", rate: 175 },

  // ── Media ──
  { id: 99, category: "Media", item: "Sony CFexpress Type A 160GB Memory Card (2-Pack Bundle)", rate: 20 },
  { id: 100, category: "Media", item: "Sony CFexpress Type A Memory Card 640GB", rate: 25 },

  // ── Monitoring ──
  { id: 101, category: "Monitoring", item: "Alvins Cables 8K 2.1 Micro HDMI to HDMI (Left-Angle, 45cm)", rate: 5 },
  { id: 102, category: "Monitoring", item: "Atomos Ninja V 5\" (x2)", rate: 75 },
  { id: 103, category: "Monitoring", item: "DJI High-Bright Monitor/Tx", rate: 125 },
  { id: 104, category: "Monitoring", item: "DJI Pro Transmission Monitor + Tx/Rx", rate: 250 },
  { id: 105, category: "Monitoring", item: "DJI RS4 Pro (x2), DJI RS3 Pro", rate: 50 },
  { id: 106, category: "Monitoring", item: "DJI Video Receiver (20,000ft, Dual-Link SDI+HDMI)", rate: 75 },
  { id: 107, category: "Monitoring", item: "DJI Video Transmitter (20,000 ft 1080p/60, Wireless Control/Playback)", rate: 75 },
  { id: 108, category: "Monitoring", item: "Duttek Micro HDMI to HDMI Coiled Cable (Right-Angle, 1ft-4ft)", rate: 5 },
  { id: 109, category: "Monitoring", item: "Hollyland Tx/Rx (x2)", rate: 75 },
  { id: 110, category: "Monitoring", item: "OSEE 15\" Production Monitor", rate: 75 },
  { id: 111, category: "Monitoring", item: "RED DSMC3 Touch 7\"", rate: 75 },

  // ── Power ──
  { id: 112, category: "Power", item: "Neewer Smart Mini V-Mount Battery PS099S (99Wh, App Control) (x4)", rate: 60 },
  { id: 113, category: "Power", item: "Neewer V-Mount Battery PS150E (150Wh, PD USB-C) (x2)", rate: 45 },
  { id: 114, category: "Power", item: "SmallRig D-TAP Dummy Battery Cable for Sony NP-FZ100 Cameras", rate: 8 },
  { id: 115, category: "Power", item: "SmallRig V Mount Battery VB212 212Wh (140W Output) (x4)", rate: 100 },
  { id: 116, category: "Power", item: "Sony NP-FZ100 Z-Series Rechargeable Battery Pack (x4)", rate: 20 },
  { id: 117, category: "Power", item: "ZGCINE VM-VP1 V-Mount Battery Adapter Plate Kit (USB-C PD/DC/D-TAP/USB-A, 15mm Rod Clamp Arm)", rate: 12 },
  { id: 118, category: "Power", item: "ZGCINE VM-VP3 V-Mount Battery Plate with USB-C PD and 3x D-TAP", rate: 15 },

  // ── Support ──
  { id: 119, category: "Support", item: "20ft Camera Crane", rate: 275 },
  { id: 120, category: "Support", item: "Advanced Ring Grip for DJI Ronin RS3 Pro / RS4 / RS4 Pro", rate: 50 },
  { id: 121, category: "Support", item: "DJI Focus Pro Creator Combo (AMF Lens Control System with LiDAR)", rate: 125 },
  { id: 122, category: "Support", item: "DJI Focus Pro LiDAR Unit (for RS 4 Pro / RS 3 Pro / Focus Pro Grip)", rate: 75 },
  { id: 123, category: "Support", item: "DJI Ronin 4D Hand Grips Combo", rate: 30 },
  { id: 124, category: "Support", item: "DRRI Nucleus-M Fischer 3-Pin to 7-Pin Run/Stop Cable for ARRI Alexa", rate: 8 },
  { id: 125, category: "Support", item: "Dana Dolly (4ft/6ft) + Riser Plate", rate: 85 },
  { id: 126, category: "Support", item: "Easyrig Vario 5 + Gimbal Vest", rate: 125 },
  { id: 127, category: "Support", item: "FX3 Underwater Housing (40m/130ft) + Seafrogs Dome Port", rate: 50 },
  { id: 128, category: "Support", item: "Glide Gear Medusa MED 100 Adjustable Body Vest (Front/Back Mount)", rate: 35 },
  { id: 129, category: "Support", item: "Glide Gear POV 100 Adjustable Helmet Camera Mount Rig", rate: 25 },
  { id: 130, category: "Support", item: "IFOOT AGE Shark Nano II Motorized Camera Slider 26in/66cm", rate: 65 },
  { id: 131, category: "Support", item: "Inovativ Voyager 42 NXT Cart System", rate: 85 },
  { id: 132, category: "Support", item: "Insta360 3m / 9.8ft Extended Edition Selfie Stick", rate: 8 },
  { id: 133, category: "Support", item: "MOFAGE PL-RF Lens Adapter Ring Kit (PL to RF Mount, Quick-Change Filter)", rate: 30 },
  { id: 134, category: "Support", item: "MOFAGE PL-Z Lens Adapter Ring Kit (PL to Nikon Z Mount, Quick-Change Filter)", rate: 30 },
  { id: 135, category: "Support", item: "Matthews Ball Heads / Microgrip Rods / Microgrip Heads", rate: 45 },
  { id: 136, category: "Support", item: "PHFX Tools Cine Filter Crate Mini 4x5.65 Filter Case", rate: 12 },
  { id: 137, category: "Support", item: "PROAIM Swift Dolly + 12ft Track", rate: 150 },
  { id: 138, category: "Support", item: "SMALLRIG 8in Lightweight ARRI Dovetail Plate (3770)", rate: 15 },
  { id: 139, category: "Support", item: "Sachtler Adapter for 75mm Aktiv Head to Slider with 3/8\"-16 Stud", rate: 10 },
  { id: 140, category: "Support", item: "Sachtler Aktiv8 Flowtech75 Tripod Systems (x2)", rate: 150 },
  { id: 141, category: "Support", item: "SeaFrogs 6in Optical Glass Dry Dome Port (78mm x 90mm)", rate: 25 },
  { id: 142, category: "Support", item: "SeaFrogs Underwater Tray with Dual Handle Grips (25x18x6 Aluminum)", rate: 15 },
  { id: 143, category: "Support", item: "Segway Ninebot S2 Self-Balancing Scooter", rate: 35 },
  { id: 144, category: "Support", item: "SmallRig 15mm Carbon Fiber Rods, 8in, Pack of 2 (870)", rate: 8 },
  { id: 145, category: "Support", item: "SmallRig 15mm Rod 4in (10cm), M12 Female Thread, Pack of 2 (1049)", rate: 8 },
  { id: 146, category: "Support", item: "SmallRig Camera Cage with Top Handle for Nikon ZR", rate: 10 },
  { id: 147, category: "Support", item: "SmallRig ZR Camera Cage Kit for Nikon ZR (5468)", rate: 15 },
  { id: 148, category: "Support", item: "Syrp Genie One Portable Motion Controller", rate: 35 },
  { id: 149, category: "Support", item: "Syrp Magic Carpet Pro + Extension", rate: 100 },
  { id: 150, category: "Support", item: "Tilta Hydra Alien Car Mounting System (V-Mount)", rate: 65 },
  { id: 151, category: "Support", item: "Tilta Hydra Electronic Suction Cup 4.5in (PD USB-C, Pressure Detection) (x3)", rate: 40 },
  { id: 152, category: "Support", item: "Tilta Hydra Car Mount System (Electronic Suction)", rate: 200 },
  { id: 153, category: "Support", item: "Tilta LS-T05 15mm LWS Y-Shaped Lens Support (Long Telescope, Quick Release)", rate: 10 },
  { id: 154, category: "Support", item: "Urth Lens Mount Adapter Leica M Lens to RF Camera Body", rate: 10 },
  { id: 155, category: "Support", item: "VILTROX E-Z Booster Lens Adapter (E-Mount Lens to Nikon Z Mount Camera)", rate: 18 },
  { id: 156, category: "Support", item: "iEago 40m/131ft Dive Case for Insta360 ONE RS 1-Inch 360 Edition", rate: 20 },
];
